### ISSUE TITLE
在处理表格时，内容包含|时无法正常解析|

### ISSUE THREAD

**Issue by ccfish86** [cevin15/MDTool#10]
处理表格时，如下，在表格中存在了转义的|(\|)时，无法正常解析

# 附录C
----------------------------------

| 字段名称            | 数据类型 | 属性描述               | 是否必填 | 最大长度 | 备注                                                                                      |
|---------------------|----------|------------------------|----------|----------|-------------------------------------------------------------------------------------------|
| cardNo              | String   | 卡号                   | 否       | 32       | 卡号                                                                                      |
| personName          | String   | 人员名称               | 否       | 32       | 长度范围1～32个字符，支持中英文字符，不包含 ' / \\ : \* ? " \< \> \|                      |
| orgIndexCode        | String   | 组织编码               | 否       | 64       | 包含数字、字母（小写）和中划线（-）                                                       |

**Comment by cevin15** [comment]
谢谢反馈~我尽快处理

**Comment by cevin15** [comment]
@ccfish86 最新代码已修复这个问题
