### ISSUE TITLE
当表格只有标题时无法解析

### ISSUE THREAD

**Issue by ZheqiangZhou** [cevin15/MDTool#11]
![微信截图_20190628160836](https://user-images.githubusercontent.com/45681697/60327644-026cd180-99bf-11e9-87f9-1d9029967630.png)

如上图所示情况下无法解析
PS:
com.youbenzi:MD2File工具可否更新一下，当导出pdf时样式和html不一样

**Comment by cevin15** [comment]
感谢反馈。我会尽快修复这个问题。
MD2File 项目很久没维护了，暂时抽不出时间来更新，还是很感谢反馈。

**Comment by cevin15** [comment]
@ZheqiangZhou 仓库中的代码已修复。晚些时候我会发布个新版到Maven 中央库

**Comment by ZheqiangZhou** [comment]
万分感谢🙏

发自我的 iPhone

在 2019年7月2日，13:36，Yingqiang <notifications@github.com<mailto:notifications@github.com>> 写道：


@ZheqiangZhou<https://github.com/ZheqiangZhou> 仓库中的代码已修复。晚些时候我会发布个新版到Maven 中央库
