### ISSUE TITLE
Messed comments in codes due to sources "Encoding" in GBK instead of UTF-8

### ISSUE THREAD

**Issue by Mararsh** [cevin15/MDTool#12]
Hi, cenvin15,
Thanks for your wonderful efforts!
I download your codes. As I read them by NetBeans, files are opened with warnings about "unsafely opened by GBK", and Chinese comments are shown in messed characters in my env although my windows is Chinese with GBK encoding. Maybe I need do more settings of Netbeans.
My projects are developed with Netbeans and their sources are always in UTF-8 encoding because I think our codes are shared with non-Chinese people too.  I write comments in English due to same reason.
In other way, Chinese comments may be the better way to share codes with Chinese developers. So no best choice~
Mara

**Comment by cevin15** [comment]
@Mararsh First, sorry for my poor English and thank you for issue.
I didn't write comments with English becaush of my poor English. I don't think I can comment clear with English. May be only myself can understand my English coments...
If you want to read the codes, you can set encoding to UTF-8. 
Thank you again for you issue :-)
