### ISSUE TITLE
*a****b*分析不对

### ISSUE THREAD

**Issue by bajie2** [cevin15/MDTool#16]
aaa \*a\*\*\*\*b\* bbb
github效果：
aaa *a****b* bbb

html：
\<p>aaa \<em>a\</em>\*\*\*b\* bbb\</p>
正确的应该是
\<p>aaa \<em>a\</em>\*\*\<em>b\</em> bbb\</p>

**Comment by cevin15** [comment]
aaa *a****b* bbb
