### ISSUE TITLE
新版本的jar貌似未修改

### ISSUE THREAD

**Issue by Hoki-Lin** [cevin15/MDTool#8]
在用IDEA导入1.2.2版本的pom后查看源码发现并没有修改关于字符集的设定,导致获取到的html字符不是UTF-8的,我再用不是UTF-8的html字符生成图片的时候,发现中文都是乱码,希望大佬马上看一下新版本的问题,谢谢。

**Comment by cevin15** [comment]
默认使用的编码是UTF-8。如果使用的是非UTF-8 编码的文件，可以使用这个方法显性指定`markdown2Html(File file, String charset)` 文件编码格式。  
不知道这样有没有解决你的问题？如果还有问题，欢迎提出。希望能有重现问题的具体步骤:-)

**Comment by cevin15** [comment]
貌似还没更新到Maven 中央库，明天更新一个小版本。

**Comment by Hoki-Lin** [comment]
OK

**Comment by cevin15** [comment]
已更新。
